name = "cors2"
main = "src/index.ts"
compatibility_date = "2022-11-24"

kv_namespaces = [
    { binding = "ANALYTICS", id = "b409efab0d634eac9c9cf575b55c6098", preview_id = "4daadfc8c22742acab5fb924892f76a9" },
]
